# Site settings
title: pbusygin.com
autor: Pavel Busygin
email: pbusygin@gmail.com
description: Просто еще один блог.
baseurl: ""
url: "https://pbusygin.github.io"
lang: ru
twitter_username: pbusygin
github_username:  pbusygin
remote_theme: "dracula/gh-pages"
show_downloads: false
show_header: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
sass:
    style: compressed
    
# Exclude from processing.
exclude:
  - Gemfile
  - CNAME
